export const colleges = [
    { label: 'Azmet College of Engineering and Technology, Kishanganj', value: 'Azmet_Kishanganj' },
    { label: 'Azmet Institute of Technology, Kishanganj', value: 'AzmetInst_Kishanganj' },
    { label: 'B P Mandal College of Engineering, Madhepura', value: 'BPMCE_Madhepura' },
    { label: 'Bakhtiyarpur College of Engineering, Bakhtiyarpur', value: 'BCE_Bakhtiyarpur' },
    { label: 'Bhagalpur College of Engineering, Bhagalpur', value: 'BCE_Bhagalpur' },
    { label: 'Buddha Polytechnic Institute, Gaya', value: 'Buddha_Gaya' },
    { label: 'Central Institute of Plastics Engineering and Technology, Hajipur', value: 'Central_Institute_of_Plastics_Engineering_and_Technology_Hajipur' },
    { label: 'CRK Polytechnic College, Hajipur', value: 'CRK_Hajipur' },
    { label: 'Darbhanga College of Engineering, Darbhanga', value: 'DCE_Darbhanga' },
    { label: 'Exalt Group of Institutions, Patna', value: 'Exalt_Patna' },
    { label: 'Ganga Memorial College of Polytechnic, Nalanda', value: 'GangaMemorial_Nalanda' },
    { label: 'Gaya College of Engineering, Gaya', value: 'GCE_Gaya' },
    { label: 'GEMS Polytechnic College, Aurangabad', value: 'GEMS_Aurangabad' },
    { label: 'Girija Devi Polytechnic College, Bhojpur', value: 'GirijaDevi_Bhojpur' },
    { label: 'Government College of Engineering, Vaishali', value: 'Government_College_of_Engineering_Vaishali' },
    { label: 'Government Engineering College, Araria', value: 'GEC_Araria' },
    { label: 'Government Engineering College, Arwal', value: 'GEC_Arwal' },
    { label: 'Government Engineering College, Aurangabad', value: 'GEC_Aurangabad' },
    { label: 'Government Engineering College, Banka', value: 'GEC_Banka' },
    { label: 'Government Engineering College, Bhojpur', value: 'GEC_Bhojpur' },
    { label: 'Government Engineering College, Buxar', value: 'Government_Engineering_College_Buxar' },
    { label: 'Government Engineering College, Gopalganj', value: 'GEC_Gopalganj' },
    { label: 'Government Engineering College, Jamui', value: 'Government_Engineering_College_Jamui' },
    { label: 'Government Engineering College, Jehanabad', value: 'GEC_Jehanabad' },
    { label: 'Government Engineering College, Kaimur', value: 'GEC_Kaimur' },
    { label: 'Government Engineering College, Khagaria', value: 'GEC_Khagaria' },
    { label: 'Government Engineering College, Kishanganj', value: 'GEC_Kishanganj' },
    { label: 'Government Engineering College, Madhubani', value: 'GEC_Madhubani' },
    { label: 'Government Engineering College, Munger', value: 'GEC_Munger' },
    { label: 'Government Engineering College, Nawada', value: 'GEC_Nawada' },
    { label: 'Government Engineering College, Sheikhpura', value: 'GEC_Sheikhpura' },
    { label: 'Government Engineering College, Sheohar', value: 'GEC_Sheohar' },
    { label: 'Government Engineering College, Siwan', value: 'GEC_Siwan' },
    { label: 'Government Engineering College, Vaishali', value: 'GEC_Vaishali' },
    { label: 'Government Engineering College, West Champaran', value: 'GEC_WestChamparan' },
    { label: 'Government Polytechnic, Barauni, Begusarai', value: 'Government_Polytechnic_Barauni_Begusarai' },
    { label: 'Government Polytechnic, Gaya', value: 'Government_Polytechnic_Gaya' },
    { label: 'Government Polytechnic, Gopalganj', value: 'Government_Polytechnic_Gopalganj' },
    { label: 'Government Polytechnic, Gulzarbagh, Patna-7', value: 'Government_Polytechnic_Gulzarbagh_Patna' },
    { label: 'Government Polytechnic, Katihar', value: 'Government_Polytechnic_Katihar' },
    { label: 'Government Polytechnic, Muzaffarpur', value: 'Government_Polytechnic_Muzaffarpur' },
    { label: 'Government Polytechnic, Purnea', value: 'Government_Polytechnic_Purnea' },
    { label: 'Government Polytechnic, Tekari, Gaya', value: 'Government_Polytechnic_Tekari_Gaya' },
    { label: 'J. P. Institute of Technology, Nalanda', value: 'JPIT_Nalanda' },
    { label: 'K. K. College of Engineering and Management, Nalanda', value: 'KK_Nalanda' },
    { label: 'Kameshwar Narayan Singh Government Polytechnic, Samastipur', value: 'Kameshwar_Narayan_Singh_Government_Polytechnic_Samastipur' },
    { label: 'Katihar Engineering College, katihar', value: 'KEC_Katihar' },
    { label: 'KK Polytechnic, Nalanda', value: 'KKPoly_Nalanda' },
    { label: 'Loknayak Jai Prakash Institute of Technology, Chapra', value: 'LNJPIT_Chapra' },
    { label: 'Millia Polytechnic, Purnea', value: 'Millia_Purnea' },
    { label: 'Motihari College of Engineering, Motihari', value: 'MCE_Motihari' },
    { label: 'Muzaffarpur Institute of Technology, Muzaffarpur', value: 'MIT_Muzaffarpur' },
    { label: 'Nalanda College of Engineering, Chandi', value: 'NCE_Nalanda' },
    { label: 'Netaji Subhas Institute of Polytechnic, Amhara, Patna', value: 'NetajiSubhas_Patna' },
    { label: 'New Government Polytechnic, Patna', value: 'New_Government_Polytechnic_Patna' },
    { label: 'Patna Sahib Group of Colleges (PSGC), Vaishali', value: 'PSGC_Vaishali' },
    { label: 'Prabhu Kailash Polytechnic, Aurangabad', value: 'PrabhuKailash_Aurangabad' },
    { label: 'Purnea College of Engineering, Purnea', value: 'PCE_Purnea' },
    { label: 'R. P. Sharma Institute of Technology, Patna', value: 'RPSharma_Patna' },
    { label: 'Rashtrakavi Ramdhari Singh Dinkar College of Engineering, Begusarai', value: 'RRDCE' },
    { label: 'Saharsa College of Engineering, Saharsa', value: 'SCE_Saharsa' },
    { label: 'Satyam International Institute of Technology, Patna', value: 'Satyam_Patna' },
    { label: 'Sershah Engineering College, Sasaram', value: 'SEC_Sasaram' },
    { label: 'Shri Ram Polytechnic, Madhubani', value: 'ShriRam_Madhubani' },
    { label: 'Sitamarhi Institute of Technology, Sitamarhi', value: 'SIT_Sitamarhi' },
    { label: 'SITYOG Institute of Technology, Aurangabad', value: 'SITYOG_Aurangabad' },
    { label: 'Supaul College of Engineering, supaul', value: 'SCE_Supaul' },
    { label: 'other', value: 'other' }
];

export const branches=[
    { label: 'B. Pharma', value: 'B_Pharma' },
    { label: 'Biomedical and Robotics Engineering', value: 'Biomedical_and_Robotics_Engineering' },
    { label: 'Civil Engineering', value: 'Civil_Engineering' },
    { label: 'Computer Science & Engineering', value: 'Computer_Science_&_Engineering' },
    { label: 'Electrical and Electronics Engineering', value: 'Electrical_and_Electronics_Engineering' },
    { label: 'Electrical Engineering', value: 'Electrical_Engineering' },
    { label: 'Electronics and Communication Engineering', value: 'Electronics_and_Communication_Engineering' },
    { label: 'Information Technology', value: 'Information_Technology' },
    { label: 'Leather Technology', value: 'Leather_Technology' },
    { label: 'Mechanical Engineering', value: 'Mechanical_Engineering' },
    { label: 'others', value: 'others' },
];

export const batches = [
    { label: "2k20", value: "2k20" },
    { label: "2k21", value: "2k21" },
    { label: "2k22", value: "2k22" },
    { label: "2k23", value: "2k23" },
];

export const tshirtSizeValue = [
{ label: "S", value: "S"},
{ label: "M", value: "M"},
{ label: "L", value: "L"},
{ label: "XL", value: "XL"},
{ label: "XXL", value: "XXL"}
];

export const knowAbout = [
  { label: "Campus Ambassador", value: "Campus Ambassador" },
  { label: "Friends", value: "Friends" },
  { label: "Social Media", value: "Social Media" },
  { label: "News and Articles", value: "News and Articles" },
  { label: "College Administration", value: "College Administration" },
  { label: "Other", value: "Other" }
];